apiVersion: v1
kind: Service
metadata:
  labels:
    app: upgrade-demo
  name: upgrade-demo
spec:
  ports:
  - name: upgrade-demo-port
    port: 4200
    targetPort: 4200
    nodePort: 30010
  selector:
    app: upgrade-demo
  type: NodePort
